# Generated by Django 5.1.2 on 2024-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.CharField(default='41a1f391-b951-4120-b7de-54135dbaabbd', max_length=50, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('SU', 'Successful'), ('FA', 'Failed')], default='PE', max_length=2)),
            ],
        ),
    ]
