# Generated by Django 5.1.2 on 2024-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.CharField(default='52e79d3c-7f41-4929-b552-c0da85d9f03c', max_length=50, primary_key=True, serialize=False),
        ),
    ]
