# Generated by Django 5.1.2 on 2024-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_bot', '0003_alter_tweets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.CharField(default='c46c2ace-7833-4380-a448-91e6a836b84f', max_length=50, primary_key=True, serialize=False),
        ),
    ]
