# Generated by Django 5.1.2 on 2024-10-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet_bot', '0005_tweets_user_alter_tweets_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='id',
            field=models.CharField(default='e5b56d70-aa9b-465e-83f5-b66e9c9afdaf', max_length=50, primary_key=True, serialize=False),
        ),
    ]
