# Generated by Django 5.1.2 on 2024-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='1ca92d7e-93ea-4ad9-a6f1-1217e7ee9ed4', max_length=50, primary_key=True, serialize=False),
        ),
    ]
