# Generated by Django 5.1.2 on 2024-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='a7a7ccdf-e175-4c70-afdb-e2b81ba146ea', max_length=50, primary_key=True, serialize=False),
        ),
    ]
