# Generated by Django 5.1.2 on 2024-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='a16916eb-4f23-4f69-8f30-c8573c583449', max_length=50, primary_key=True, serialize=False),
        ),
    ]
