# Generated by Django 5.1.2 on 2024-10-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ea857aec-f502-49b4-bfce-260e29538945', max_length=50, primary_key=True, serialize=False),
        ),
    ]
