# Generated by Django 5.1.2 on 2024-10-17 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='74f74d4c-7d45-45f6-ba23-8d62c6fd81b2', max_length=50, primary_key=True, serialize=False),
        ),
    ]
