# Generated by Django 5.1.2 on 2024-10-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_refresh_token_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='512947a8-05cf-4f91-adf8-15806fb95b24', max_length=50, primary_key=True, serialize=False),
        ),
    ]
