# Generated by Django 5.1.2 on 2024-10-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='54abd8ed-89e5-4a53-9075-06578349d5db', max_length=50, primary_key=True, serialize=False),
        ),
    ]
